name: 🚀 Release

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Release type: patch, minor or major'
        required: true
        default: 'patch'
      dry_run:
        description: 'Dry run only?'
        required: true
        default: 'true'
      skip_tests:
        description: 'Skip tests?'
        required: true
        default: 'false'
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - name: Checkout code (with full history & tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run tests
        if: ${{ github.event.inputs.skip_tests == 'false' }}
        run: cargo test --workspace --all-features

      - name: Install cargo-release
        run: |
          # pin to a known-good version
          cargo install cargo-release --version 0.25.18 --locked

      - name: Configure Git for tagging
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version & tag
        # if the tag already exists, we don’t want the whole job to fail
        continue-on-error: true
        run: |
          REL_TYPE=${{ github.event.inputs.type }}
          DRY=${{ github.event.inputs.dry_run }}
          if [ "$DRY" = "false" ]; then
            # execute the bump, commit and tag
            cargo release $REL_TYPE --execute --no-publish --no-verify
          else
            # dry-run: show what would happen
            cargo release $REL_TYPE --no-publish --no-verify
          fi

      - name: Publish to crates.io
        if: ${{ github.event.inputs.dry_run == 'false' }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          # after bump/tag, actually publish the crate
          cargo publish --token $CARGO_REGISTRY_TOKEN
